---
- hosts: prod
  become: yes
  vars:
          package: httpd 

  tasks:
          - name: install a application
            apt: 
                name: "{{package}}" 
                state: present

            


